image: php:8.2-fpm

pipelines:
  default:
    - step:
        name: Install Dependencies
        script:
          - apt-get update && apt-get install -qy git curl libmcrypt-dev
          - yes | pecl install mcrypt-1.0.7
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          - source ~/.nvm/nvm.sh
          - nvm install 18
          # - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          # - php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          # - php composer-setup.php
          # - php -r "unlink('composer-setup.php');"
          # - mv composer.phar /usr/local/bin/composer
          - composer install --no-interaction --prefer-dist --optimize-autoloader
          - cp .env.example .env
          - npm ci
          - npm run build
          # - php artisan key:generate
          # Run Laravel tests if available
          # - php artisan test || true
        artifacts:
          - public/build # means need to save dist folder and copy to next step
          - public/build/**
        caches:
          - composer
          - node

    - step:
        name: Deploy app
        script:
          - "echo 'cd /home/imagetim/staging.sbp.imageandtime.com' > sbpscript.sh"
          - "echo 'git pull' > sbpscript.sh"
          - "echo 'composer install' > sbpscript.sh"
          - "echo 'php artisan migrate --force' > sbpscript.sh"
          - "echo 'rsync -r -e 'ssh -p $SSH_USERNAME' /public/build/ $SSH_USERNAME@$SSH_HOST:/home/imagetim/staging.sbp.imageandtime.com/public/build' > sbpscript.sh"
          - pipe: atlassian/ssh-run:0.8.0
            variables:
              SSH_USER: $SSH_USERNAME
              SERVER: $SSH_HOST
              PORT: $SSH_PORT # Optional
              SSH_KEY: $SSH_KEY
              MODE: "script"
              COMMAND: "sbpscript.sh" # path to a script in your repository
